#!/usr/bin/env bash

ROOT=$(dirname $0)

has_param() {
    local term="$1"
    shift
    for arg; do
        if [[ $arg == "$term" ]]; then
            return 0
        fi
    done
    return 1
}

. $ROOT/../../scripts/flags/declares.sh

variables["-o"]="output"
variables["--engine"]="engine"
variables["--times"]="times"
variables["--weights"]="weights"
variables["--split"]="split"

. $ROOT/../../scripts/flags/arguments.sh

output=${output:-"/tmp/tests"}
engine=${engine:-""}
times=${times:-"10"}
weights=${weights:-""}
split=${split="full_75_25"}

. $ROOT/../cases.sh

train_weights_flag=""
eval_weights_flag=""
if [ "$weights" != "" ]; then
    train_weights_flag="--model.save_path $weights"
    eval_weights_flag="--model.path $weights"
fi

engine_flag=""
if [ "$engine" != "" ]; then
    engine_flag="--engine $engine"
fi

echo >> $output
if [ "$engine" != "" ]; then
    echo "DENSENET TESTS USING $engine" >> $output
else
    echo "DENSENET TESTS" >> $output
fi

for config_path in ${test_cases[*]}; do
    if [ ! -f "$config_path" ] || [ "${config_path: -5}" != ".conf" ]; then
        continue
    fi

    if ! has_param '--is-split' "$@"; then
        echo >> $output
        echo "EXECUTING TEST CASE WITH CONFIG AT $config_path"
        echo "EXECUTING TEST CASE WITH CONFIG AT $config_path" >> $output

        python $ROOT/../../src/densenet/scripts/train/run_train.py --config $config_path --data.split ${split} $engine_flag $train_weights_flag
        python $ROOT/../../src/densenet/scripts/eval/run_eval.py --config $config_path --data.split ${split} $engine_flag $eval_weights_flag >> $output
    else
        split=""
        if [ "${config_path: -7}" = "_5.conf" ]; then split="5_samples"; fi
        if [ "${config_path: -7}" = "10.conf" ]; then split="10_samples"; fi
        if [ "${config_path: -7}" = "15.conf" ]; then split="15_samples"; fi
        if [ "${config_path: -7}" = "20.conf" ]; then split="20_samples"; fi
        if [ "${config_path: -7}" = "30.conf" ]; then split="30_samples"; fi

        for i in $(seq 1 $times); do
            echo >> $output
            echo "EXECUTING TEST CASE WITH CONFIG AT $config_path WITH SPLIT ${split}_$i"
            echo "EXECUTING TEST CASE WITH CONFIG AT $config_path WITH SPLIT ${split}_$i" >> $output

            echo "Running python $ROOT/../../src/densenet/scripts/train/run_train.py --config $config_path --data.split ${split}_$i $engine_flag $train_weights_flag"
            python $ROOT/../../src/densenet/scripts/train/run_train.py --config $config_path --data.split ${split}_$i $engine_flag $train_weights_flag
            echo "Running python $ROOT/../../src/densenet/scripts/eval/run_eval.py --config $config_path --data.split ${split}_$i $engine_flag $eval_weights_flag"
            python $ROOT/../../src/densenet/scripts/eval/run_eval.py --config $config_path --data.split ${split}_$i $engine_flag $eval_weights_flag >> $output
        done
    fi

    echo >> $output
done
