#!/usr/bin/env bash

ROOT=$(dirname $0)

has_param() {
    local term="$1"
    shift
    for arg; do
        if [[ $arg == "$term" ]]; then
            return 0
        fi
    done
    return 1
}

. $ROOT/../../scripts/flags/declares.sh

variables["-o"]="output"
variables["--engine"]="engine"
variables["--times"]="times"
variables["--weights"]="weights"

. $ROOT/../../scripts/flags/arguments.sh

output=${output:-"/tmp/tests"}
engine=${engine:-""}
times=${times:-"10"}
weights=${weights:-""}

. $ROOT/../cases.sh

train_weights_flag=""
eval_weights_flag=""
if [ "$weights" != "" ]; then
    train_weights_flag="--model.save_path $weights"
    eval_weights_flag="--model.path $weights"
fi

engine_flag=""
if [ "$engine" != "" ]; then
    engine_flag="--engine $engine"
fi

echo >> $output
if [ "$engine" = "" ]; then
    echo "DenseNet tests using $engine" >> $output
else
    echo "DenseNet tests" >> $output
fi

for config_path in ${test_cases[*]}; do
    if [ ! -f "$config_path" ] || [ "${config_path: -5}" != ".conf" ]; then
        continue
    fi

    echo >> $output
    echo "Executing test case with config at $config_path"
    echo "Executing test case with config at $config_path" >> $output

    python $ROOT/../../src/densenet/scripts/train/run_train.py --config $config_path $engine_flag $train_weights_flag
    python $ROOT/../../src/densenet/scripts/eval/run_eval.py --config $config_path $engine_flag $eval_weights_flag --times $times >> $output

    echo >> $output
done
