#!/usr/bin/env bash

ROOT=$(dirname $0)

has_param() {
    local term="$1"
    shift
    for arg; do
        if [[ $arg == "$term" ]]; then
            return 0
        fi
    done
    return 1
}

. $ROOT/../../scripts/flags/declares.sh

variables["-o"]="output"

. $ROOT/../../scripts/flags/arguments.sh

output=${output:-"/tmp/tests"}

. $ROOT/../cases.sh

echo >> "$output"
echo "Transfer Learning tests with DenseNet" >> "$output"

for config_path in ${test_cases[*]}; do
    if [ ! -f "$config_path" ] || [ "${config_path: -5}" != ".conf" ]; then
        continue
    fi

    echo "Executing test case with config at $config_path"
    echo "Executing test case with config at $config_path" >> "$output"

    python $ROOT/../../src/transfer_learning/scripts/train/run_train.py --config $config_path
    for i in {1..10}; do
        python $ROOT/../../src/transfer_learning/scripts/eval/run_eval.py --config $config_path >> "$output"
    done
done
